import { getVersion, getToolName } from './pkg';

export const writeFileHeader = (name, description) => {
    return `
    /**
     * -----------------------------------
     * ${name}
     * -----------------------------------
     * ${description} 
     *
     * This is a generated file, do not directly edit. It was generated from the 
     * openapi spec defined in your project. 
     * 
     * Generated by ${getToolName()}@${getVersion()}
     */
    `;
}
